### ISSUE TITLE
Removes empty initialize methods: Style/RedundantInitialize: Remove unnecessary empty `initialize` method.

### ISSUE THREAD

**Issue by dorianmariefr** [standardrb/standard#602] opened 2024-01-31 11:12 UTC
Before:

```ruby
class A
  def initialize
    raise NotImplementedError
  end
end

class B < A
  def initialize
  end
end

puts B.new
```

After:

```ruby
# frozen_string_literal: true

class A
  def initialize
    raise NotImplementedError
  end
end

class B < A
end

puts B.new
```

```
> standardrb -v
1.33.0
```

**Comment by al2o3cr** [comment] 2024-02-05 17:09
This is also troublesome if the empty `initialize` takes arguments:

```
class A
  def initialize(not_used)
    # this space intentionally left blank
  end
end

a_variable_instead_of_some_kind_of_lookup = A

a_variable_instead_of_some_kind_of_lookup.new("foo")
```

Just had this happen on a client project.

**Comment by searls** [comment] 2024-02-06 14:35
Makes sense :+1:. Standard should be skeptical of any cop that runs the risk of screwing up the user's intended behavior, and it's clear there are too many uncovered edge cases for this cop to be acceptable.

In the future, it'd be helpful to link to the RuboCop docs and share Standard's current configuration (in this case: [Style/RedundantInitialize](https://docs.rubocop.org/rubocop/cops_style.html#styleredundantinitialize) and

```yaml
Style/RedundantInitialize:
  Enabled: true
```

**Comment by jasonkarns** [comment] 2024-02-06 15:31
Worth noting that this cop is not Safe per rubocop's metadata. I presume that we are less likely to enable cops that are not safe.

**Comment by czeise** [comment] 2024-02-06 16:00
> Worth noting that this cop is not Safe per rubocop's metadata. I presume that we are less likely to enable cops that are not safe.

Definitely. It looks like [this particular cop wasn't initially marked as unsafe](https://github.com/rubocop/rubocop/pull/10527) until this same issue was identified.

**Closed** 2024-02-06 16:37 UTC
Labels: rule change 👩‍⚖️

**Comment by dorianmariefr** [comment] 2024-02-07 08:41
Thanks all
